import { API_GATEWAY_NOTIFICATION_TO_NOTIFICATION_MICROSERVICE_KAFKA_REGISTRY } from "./registry/kafka.registry";
import { NOTIFICATION_MICROSERVICE_TCP_REGISTRY } from "./registry/tcp.registry";

export const MODULE_CONFIG = {
  transport: process.env.NOTIFICATION_MICROSERVICE_TRANSPORT,
  TCP: NOTIFICATION_MICROSERVICE_TCP_REGISTRY,
  KAFKA: API_GATEWAY_NOTIFICATION_TO_NOTIFICATION_MICROSERVICE_KAFKA_REGISTRY,
};
