import { CMS_MICROSERVICE_TCP_REGISTRY } from "./registry/tcp.registry";
import { API_GATEWAY_TESTIMOINIAL_TO_CMS_MICROSERVICE_KAFKA_REGISTRY } from "./registry/kafka.registry";
export const MODULE_CONFIG = {
  transport: process.env.CMS_MICROSERVICE_TRANSPORT,
  TCP: CMS_MICROSERVICE_TCP_REGISTRY,
  KAFKA: API_GATEWAY_TESTIMOINIAL_TO_CMS_MICROSERVICE_KAFKA_REGISTRY,
  REDIS: {},
  RABBITMQ: {},
};
