import { API_GATEWAY_TAX_TO_MASTER_MICROSERVICE_KAFKA_REGISTRY } from "./registry/kafka.registry";
import { MASTER_MICROSERVICE_TCP_REGISTRY } from "./registry/tcp.registry";

export const MODULE_CONFIG = {
  transport: process.env.MASTER_MICROSERVICE_TRANSPORT,
  TCP: MASTER_MICROSERVICE_TCP_REGISTRY,
  KAFKA: API_GATEWAY_TAX_TO_MASTER_MICROSERVICE_KAFKA_REGISTRY,
  REDIS: {},
  RABBITMQ: {},
};
