import { MASTER_MICROSERVICE_TCP_REGISTRY } from "./registry/tcp.registry";
import { API_GATEWAY_BRAND_TO_MASTER_MICROSERVICE_KAFKA_REGISTRY } from "./registry/kafka.registry";
export const MODULE_CONFIG = {
  transport: process.env.MASTER_MICROSERVICE_TRANSPORT,
  TCP: MASTER_MICROSERVICE_TCP_REGISTRY,
  KAFKA: API_GATEWAY_BRAND_TO_MASTER_MICROSERVICE_KAFKA_REGISTRY,
  REDIS: {},
  RABBITMQ: {},
};
